<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <title>Note</title>
</head>
<body>
    <header>
        <div class="content">
            <h1>NOTE</h1>
            <div class="user">
                <div class="btn" style="width: 30px;">Sair</div>
            </div>
        </div>
    </header>
    <div class="content">
        <div class="menu">
            <ul>
                <li><div class="btn btn-menu">Tarefas</div></li>
                <li><div class="btn btn-active">Projetos</div></li>
                <li></li>
            </ul>
        </div>
        <div class="task">
            <form action="/" method="post" autocomplete="off">
                <input type="text" placeholder="Nova tarefa" name="task" autofocus>
            </form>
            <ul>
                <?php foreach ($tasks as $task) { ?>
                <li>
                    <?= $task ?>
                    <a class="del" href=""><i class="material-icons">clear</i></a>
                </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</body>
</html>